---

- hosts: webidn
  gather_facts: False
  tasks:
  - name: root ssh passwordless
    authorized_key: user=root
                    exclusive=no
                    key="{{ lookup('file', '~/.ssh/id_rsa.pub')}}"
